version: "3.4"

services:
  bitly:
    build: bitly
    image: bitly
    restart: "no"
    volumes:
      - ./bitly/:/app
    ports:
      - 7777:7777
    depends_on:
      - database3
      - flyway
    env_file:
      - project.env

  database3:
    container_name: database3_python
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database3
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env